### ISSUE TITLE
Enum defined twice if `@id` is also marked with `@unique`

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#71] opened 2022-05-28 17:21 UTC
```
   Compiling glowsquid v0.1.0 (/mnt/BulkStorage/projects/github.com/glowsquid-launcher/glowsquid/apps/oxidize)
error[E0428]: the name `IdEquals` is defined multiple times
   --> src/prisma.rs:875:5
    |
873 |     IdEquals(String),
    |     ---------------- previous definition of the type `IdEquals` here
874 |     UsernameEquals(String),
875 |     IdEquals(String),
    |     ^^^^^^^^^^^^^^^^ `IdEquals` redefined here
    |
    = note: `IdEquals` must be defined only once in the type namespace of this enum

For more information about this error, try `rustc --explain E0428`.
error: could not compile `glowsquid` due to previous error

[Process exited 0]
```

schema:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "cargo prisma"
  output   = "../src/prisma.rs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

/// A minecraft account
model Account {
  /// The account's unique id
  id            String   @id @unique // <-- issue is here
  /// The account's username
  username      String   @unique

}
```

**Comment by Suyashtnt** [comment] 2022-05-28 19:08
My current guess is that because Im telling the `@id` is `@unique` it adds it to the iterator twice

**Comment by Suyashtnt** [comment] 2022-05-28 19:10
Just removed `@unique`, can confirm it was the issue. Keeping this issue open until that edge case is fixed

**Comment by Brendonovich** [comment] 2022-05-29 08:34
This should be fixed, try using `rev = "6adf53dae0ea1e3a54bb439d69fbfceff8b90f15"` instead of `tag = "0.5.0"`

**Comment by Brendonovich** [comment] 2022-06-02 08:57
@Suyashtnt Would be great if you could verify whether this is fixed, I'd like to release an update by the end of the week.

**Comment by Suyashtnt** [comment] 2022-06-02 13:03
> @Suyashtnt Would be great if you could verify whether this is fixed, I'd like to release an update by the end of the week.

I'll test with my other project soon:TM:

**Comment by Brendonovich** [comment] 2022-06-06 05:05
I'm going to close this as fixed, since I haven't been able to reproduce the error after 6adf53dae0ea1e3a54bb439d69fbfceff8b90f15

**Closed by Brendonovich** 2022-06-06 05:05 UTC
Labels: bug, codegen
