### ISSUE TITLE
Prisma cli build failed

### ISSUE THREAD

**Issue by Alivers** [Brendonovich/prisma-client-rust#256] opened 2023-02-21 09:04 UTC
My Cargo.toml config:  
```
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.4" }
```

Prisma cli build failed with the error: 
```
  Compiling quaint v0.2.0-alpha.13 (https://github.com/prisma/quaint?rev=fb4fe90682b4fecb485fd0d6975dd15a3bc9616b#fb4fe906)
error[E0599]: no method named `with_pkcs12_path` found for struct `SslOpts` in the current scope
   --> /Users/aliver/.cargo/git/checkouts/quaint-9f01e008b9a89c14/fb4fe90/src/connector/mysql.rs:187:41
    |
187 |                     ssl_opts = ssl_opts.with_pkcs12_path(Some(Path::new(&*v).to_path_buf()));
    |                                         ^^^^^^^^^^^^^^^^ method not found in `SslOpts`

error[E0599]: no method named `with_password` found for struct `SslOpts` in the current scope
   --> /Users/aliver/.cargo/git/checkouts/quaint-9f01e008b9a89c14/fb4fe90/src/connector/mysql.rs:191:41
    |
191 |                     ssl_opts = ssl_opts.with_password(Some(v.to_string()));
    |                                         ^^^^^^^^^^^^^ method not found in `SslOpts`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `quaint` due to 2 previous errors
```

**Comment by Alivers** [comment] 2023-02-21 09:18
quaint update mysql_async dependency 19h ago. How can we upgrade to fix this break changes?
https://github.com/prisma/quaint

**Comment by Brendonovich** [comment] 2023-02-23 05:42
I'm pretty sure this couldn't have been solved with `[patch]` since it's to do with nested git dependencies. I've forked `quaint` and locked it to a specific commit of `mysql_async`. Try using `rev = "6fbef57fcd08fd1daeb70b49b14f5144b15898aa"` of the engines.

**Comment by Alivers** [comment] 2023-02-23 12:56
After I change rev to `6fbef57fcd08fd1daeb70b49b14f5144b15898aa`, the generated code did not work with my project. 
The error is: 
```bash
error[E0425]: cannot find function `is_empty` in module `snapshot_meta::error_versions`
   --> src/core/prisma_processor_metadata.rs:185:48
    |
185 |                 snapshot_meta::error_versions::is_empty(false),
    |                                                ^^^^^^^^ not found in `snapshot_meta::error_versions`

error[E0425]: cannot find function `is_empty` in module `snapshot_meta::interested_versions`
   --> src/core/prisma_processor_metadata.rs:208:53
    |
208 |                 snapshot_meta::interested_versions::is_empty(false),
    |                                                     ^^^^^^^^ not found in `snapshot_meta::interested_versions`
``` 

And also, my `schema.prisma` definition has no change, above two fields are defined in `Bigint[]`:
```prisma
    interested_versions BigInt[]
    error_versions      BigInt[]
```

**Comment by Brendonovich** [comment] 2023-02-23 14:09
Hmm, using `mysql` I'm not even allowed to use `BigInt[]` as a field type - `postgresql` works though, and that doesn't have the `is_empty` filter. That's on both 0.6.4 and `6fbef57fcd08fd1daeb70b49b14f5144b15898aa`.

**Comment by Alivers** [comment] 2023-02-23 14:11
Sorry, I missed the db. I'm using mongodb, a few days ago I am using 0.6.3, it works correctly.

**Comment by Brendonovich** [comment] 2023-02-23 14:24
Ohh you're not using `default-features = false, features = ["mongodb"]`, gotcha. Looks like a regression to do with scalar lists. Will be fixed soon.

**Comment by Alivers** [comment] 2023-02-23 14:37
Thanks for your insight and reminder! I really should use `default-features = false, features = ["mongodb"]` to avoid unnecessary build.

**Comment by Brendonovich** [comment] 2023-02-23 15:43
@Alivers check new issue for fix: https://github.com/Brendonovich/prisma-client-rust/issues/257

**Closed** 2023-03-02 06:34 UTC
Labels: bug, lib

**Comment by MachariaK** [comment] 2023-03-03 12:17
The proposed fix is not working for me. 

Cargo.toml:

`prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", rev = "1f6474396363bab8c4cdd70c342055779b36909d" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", rev = "1f6474396363bab8c4cdd70c342055779b36909d" }
`
Error:

`error[E0433]: failed to resolve: could not find `ClientIdentity` in `mysql_async`
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:282:45
    |
282 |                 let identity = mysql_async::ClientIdentity::new(path).with_password(pw);
    |                                             ^^^^^^^^^^^^^^ could not find `ClientIdentity` in `mysql_async`

error[E0433]: failed to resolve: could not find `ClientIdentity` in `mysql_async`
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:286:45
    |
286 |                 let identity = mysql_async::ClientIdentity::new(path);
    |                                             ^^^^^^^^^^^^^^ could not find `ClientIdentity` in `mysql_async`

error[E0599]: no method named `with_client_identity` found for struct `SslOpts` in the current scope
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:283:26
    |
283 |                 ssl_opts.with_client_identity(Some(identity))
    |                          ^^^^^^^^^^^^^^^^^^^^ method not found in `SslOpts`

error[E0599]: no method named `with_client_identity` found for struct `SslOpts` in the current scope
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:287:26
    |
287 |                 ssl_opts.with_client_identity(Some(identity))
    |                          ^^^^^^^^^^^^^^^^^^^^ method not found in `SslOpts`

Some errors have detailed explanations: E0433, E0599.       
For more information about an error, try `rustc --explain E0433`.
error: could not compile `quaint` due to 4 previous errors `

**Comment by Brendonovich** [comment] 2023-03-03 12:20
@MachariaK Does using version 0.6.5 fix this? I have seen those errors before.

**Comment by MachariaK** [comment] 2023-03-03 12:25
> @MachariaK Does using version 0.6.5 fix this? I haven't seen those errors before.

Doesn't fix.

I am getting the following errors:

error[E0433]: failed to resolve: could not find `ClientIdentity` in `mysql_async`
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:282:45
    |
282 |                 let identity = mysql_async::ClientIdentity::new(path).with_password(pw);
    |                                             ^^^^^^^^^^^^^^ could not find `ClientIdentity` in `mysql_async`

error[E0433]: failed to resolve: could not find `ClientIdentity` in `mysql_async`
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:286:45
    |
286 |                 let identity = mysql_async::ClientIdentity::new(path);
    |                                             ^^^^^^^^^^^^^^ could not find `ClientIdentity` in `mysql_async`

error[E0599]: no method named `with_client_identity` found for struct `SslOpts` in the current scope
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:283:26
    |
283 |                 ssl_opts.with_client_identity(Some(identity))
    |                          ^^^^^^^^^^^^^^^^^^^^ method not found in `SslOpts`

error[E0599]: no method named `with_client_identity` found for struct `SslOpts` in the current scope
   --> C:\Users\Tim\.cargo\git\checkouts\quaint-453f07acedd929b5\b12fef8\src\connector\mysql.rs:287:26
    |
287 |                 ssl_opts.with_client_identity(Some(identity))
    |                          ^^^^^^^^^^^^^^^^^^^^ method not found in `SslOpts`

Some errors have detailed explanations: E0433, E0599.       
For more information about an error, try `rustc --explain E0433`.
error: could not compile `quaint` due to 4 previous errors

**Comment by Brendonovich** [comment] 2023-03-05 05:32
@MachariaK Does `cargo update -p prisma-client-rust` fix things?

**Comment by MachariaK** [comment] 2023-03-05 09:10
> @MachariaK Does `cargo update -p prisma-client-rust` fix things?

Running perfectly now.
